Rolled back + added ls for mingw

diff --git a/.github/workflows/ci_tests.yml b/.github/workflows/ci_tests.yml
--- a/.github/workflows/ci_tests.yml
+++ b/.github/workflows/ci_tests.yml
@@ -49,7 +49,7 @@ jobs:
       - name: Build main target
         shell: bash
         run: |
-          cmake --build cmake-build-release || echo "Built with errors"
+          cmake --build cmake-build-release --target cpp_tests || echo "Built with errors"
 
       - name: Build tests target
         shell: bash
@@ -77,6 +77,7 @@ jobs:
         run: |
           if [ "$RUNNER_OS" == "Windows" ]; then
               if [ "${{ matrix.config.cxx }}" == "g++" ]; then
+                ls -La
                 ./cpp_tests_tests.exe
               else 
                 ./cpp_tests_tests.exe
